fof(axiom,axiom,
    ?[BN_1] :
        (triple(
            list(
                '"1"^^http://www.w3.org/2001/XMLSchema#integer',
                list(
                    BN_1,
                    list(
                        list(
                            '"2"^^http://www.w3.org/2001/XMLSchema#integer',
                            'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                        ),
                        'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                    )
                )
            ),
            'http://example.org/stuff/1.0/p2',
            'http://example.org/stuff/1.0/q2'
        )
        &
        triple(BN_1,'http://example.org/stuff/1.0/p','http://example.org/stuff/1.0/q'))).