fof(axiom,axiom,
    triple(
        list(
            '"1"^^http://www.w3.org/2001/XMLSchema#integer',
            list(
                '"2"^^http://www.w3.org/2001/XMLSchema#decimal',
                list(
                    '"30.0"^^http://www.w3.org/2001/XMLSchema#double',
                    'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                )
            )
        ),
        'http://example.org/stuff/1.0/p',
        '"w"^^http://www.w3.org/2001/XMLSchema#string'
    )
).