fof(axiom,axiom,
    ?[T,M,BN_1]:(
        triple(
            T,
            'http://example.org/foopredicate',
            list(
                'http://example.org/fooA',
                list(
                    'http://example.org/fooB',
                    list(
                        'http://example.org/fooC',
                        'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                    )
                )
            )
        )
        &
        ?[T]: (
                triple(
                    'http://example.org/foosubject',
                    'http://example.org/foopredicate2',
                    'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                )
             )
             &
             ![T,O]: ~(
                triple(
                    'http://example.org/foosubject',
                    'http://example.org/foopredicate2',
                    list(
                        'http://example.org/fooC',
                        list(
                            'http://example.org/fooF',
                            list(
                                list(
                                    'http://example.org/fooL',
                                    list(
                                        M,
                                        list(
                                            BN_1,
                                            'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                                        )
                                    )
                                ),
                                'http://www.w3.org/1999/02/22-rdf-syntax-ns#nil'
                            )
                        )
                    )
                )
                &
                triple(
                    BN_1,
                    'http://example.org/fooA',
                    'http://example.org/fooC'
                )
             )
        )
    ).