#!/bin/bash
FILES="eye/reasoning/blogic/*.n3s"
RE=0
for f in $FILES
do
  if [[ $f = *answer.n3s ]]; then continue ; fi
  echo -n "Processing $f file...  -   "
  ./bin/rs2fol check -q -i $f -e /vampire_z3_rel_qa_6176 # --vampire-option-mode 1 --rdf-list
  ((RE++))
done
echo "Number of processed files: $RE"