#!/bin/bash
# NOTE : Quote it else use array to avoid problems #
FILES="/home/rebekka/Programs/EyeReasoner/eye/reasoning/blogic/*.n3s"
RE=0
for f in $FILES
do
  if [[ $f = *answer.n3s ]]; then continue ; fi
  echo  "Processing $f file...  -------   "
  ./bin/untitled1 transform-with-qa -q -i "$f" --vampire-option 1
  ((RE++))
done
echo "Number of processed files: $RE"