#!/bin/bash
# NOTE : Quote it else use array to avoid problems #
FILES="/home/rebekka/Programs/EyeReasoner/eye/reasoning/blogic/*.n3"
RE=0
for f in $FILES
do
  if [[ $f = *answer.n3 ]]; then continue ; fi
  # echo "Processing $f file..."
  ./bin/untitled1 transform --path $f
  ((RE++))
done
echo "Number of processed files: $RE"