#!/bin/bash

# Create your own .env file with the missing variables within the rs2fol file
source ../../.env

# Prepare results directory
mkdir -p results

# Define the number of runs
NUM_RUNS=100

FILES="supported/*.n3s"

# Initialize the CSV file with header
CSV_FILE="results/eye-runtime-100.csv"
echo "file,average_runtime_ns" > "$CSV_FILE"

# Loop over each file
for file in $FILES; do

    FILENAME=$(basename "$file")

    if [ "$FILENAME" == "peano.n3s" ]; then
        echo "Jump over $FILENAME"
        continue
    fi

    echo "Measuring for $file"

    # Initialize the total runtime
    total_runtime=0

    # Loop to perform the measurements
    for ((i=1; i<=NUM_RUNS; i++))
    do
        echo "Measurement $i of $NUM_RUNS"

        start_time=$(date +%s%N)  # Start time in nanoseconds
        RESULT=$(eye --nope --no-bnode-relabeling --quiet "$file")
        end_time=$(date +%s%N)  # End time in nanoseconds

        # Calculate the runtime in nanoseconds and add it to the total runtime
        runtime=$((end_time - start_time))
        echo "Runtime: $runtime ns"
        total_runtime=$((total_runtime + runtime))
    done

    # Calculate the average runtime
    average_runtime=$((total_runtime / NUM_RUNS))
    echo "Average runtime for $file: $average_runtime ns"
    echo ""

    # Save the results to the CSV file
    echo "$(basename "$file"),$average_runtime" >> "$CSV_FILE"
done
