#!/bin/bash
FILES="/home/rebekka/Programs/EyeReasoner/rdfsurfaces-tests/test/*.n3s"
PATH_TO_VAMPIRE="/home/rebekka/Programs/Vampire-qa/tmp/build/bin/vampire_z3_rel_qa_6176"
RE=0
for f in $FILES
do
  echo -n "Processing $f file...  -   "
  new_path="$f.out"
  /home/rebekka/Projects/rs2fol/bin/rs2fol check -q -i "$f" -e $PATH_TO_VAMPIRE -c "$new_path" # --rdf-list
  ((RE++))
done
echo "Number of processed files: $RE"