#!/bin/bash
FILES="*.n3"
PATH_TO_VAMPIRE="/PATH/tmp/build/bin/vampire_z3_rel_qa_6176"
RE=0
for f in $FILES
do
  echo "Processing $f file...  -------   "
  /PATH/rs2fol/bin/rs2fol transform-qa -q -i "$f" -e $PATH_TO_VAMPIRE # -v 1
  ((RE++))
done
echo "Number of processed files: $RE"